permalink: /:year-:month/:title/
title: 听雨人
email: contact@zzeyu.com
description: 一些纯粹的思考
hgimgcount: 8

paginate: 5
paginate_path: "/:num/"

navigation:
  - text: Home
    url: /
  - text: About
    url: /about.html
  - text: Categories
    url: /categories.html
  - text: Tags
    url: /tags.html

read_more: Read More
env: production
minify_html: true # Set to true only when it is production. Increase significant build time.

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE