permalink: /:year-:month/:title/
title: 听雨人
email: contact@zzeyu.com
description: 一些纯粹的思考
hgimgcount: 8
url: http://gitblog.zzeyu.com

paginate: 5
paginate_path: "/page:num/"

navigation:
  - text: RSS
    url: /feed.xml

env: production
minify_html: true # Set to true only when it is production. Increase significant build time.

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

gems:
  - jekyll-paginate
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
