permalink: /:year-:month/:title/
title: 听雨人
email: contact@zzeyu.com
description: 一些纯粹的思考
hgimgcount: 8
url: http://www.rainaudience.net

paginate: 5
paginate_path: "/page:num/"

navigation:
  - text: 订阅RSS
    url: /feed.xml
  - text: 我的相册集
    url: /gallery
  - text: LOFTER
    url: http://zzy8200.lofter.com/

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"

compress_html:
  clippings: all
  comments: ["<!--m", "-->"]
  blanklines: false

gems:
  - jekyll-paginate
  
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE